### ISSUE TITLE
可以出一份不用docker安装的，毕竟docker有人不懂

### ISSUE THREAD

**Issue by iusky** [erevus-cn/pocscan#10]
可以出一份不用docker安装的，毕竟docker有人不懂
比如我：P

**Comment by erevus-cn** [comment]
1.首先安装依赖环境sudo pip install -r requirements.txt
2.安装rabbitmq，启动rabbitmq-server。(我mac下是sudo /usr/local/sbin/rabbitmq-server)
3.启动celery,cd到代码根目录 python manage.py celery worker  -l info
4.数据库同步,python manage.py syncdb,  输入用户名密码
5.启动web界面,python manage.py runserver 127.0.0.1:8081 (端口必须8081，如果要用其他端口,需要修改setting.py里的SAVE_RESULT_API = "http://127.0.0.1:8081/save_result")
6.最后,不推荐试用非docker方式.用docker是便于你们搭建... ：D
