### ISSUE TITLE
求教爬虫功能与sqlmap的正确姿势

### ISSUE THREAD

**Issue by ghost** [erevus-cn/pocscan#12]
第一时间试用了下，爬虫与sqlmap功能不理想。
第一：爬虫只爬首页？
测试发现就爬取了下目标url。爬取深度为1......
第二：sqlmap是手动调用的？
自己选中url，点击“To sqlmap“此时sqlmap才会对目标测试吗？是否繁琐了一些？
谢谢。

**Comment by erevus-cn** [comment]
1.爬虫算法是广度遍历爬行 但是只会爬当前host.深度是3
2.因为爬虫会把一些奇怪的静态文件也抓过来丢到sqlmap里,现在暂时是需要手工添加,后续版本会改成白名单爬行然后自动添加到sqlmap

**Comment by ghost** [comment]
大牛，bilibili工资多少？

**Comment by erevus-cn** [comment]
参考拉勾和主站上的招聘
