### ISSUE TITLE
指定celery backend

### ISSUE THREAD

**Issue by xiaoxiaoleo** [erevus-cn/pocscan#13]
在setting中添加CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend',
不然会导致无法获取result,参考https://github.com/celery/django-celery/issues/227。。

**Comment by erevus-cn** [comment]
喵喵喵???没理解你的意思

**Comment by xiaoxiaoleo** [comment]
执行一个任务，比如c  = add.delay(4,0) 然后通过 c.get()是无法获取result的。 。。。

**Comment by erevus-cn** [comment]
我是把结果都用http的方式发到127.0.0.1的一个接口上了 没用get()这种方式.因为用gevent的时候出现了数据库的写入锁问题,所以用了http这种中转结果的方式

**Comment by xiaoxiaoleo** [comment]
嗷嗷，感觉这样网站请求数据量会比较大吧，，

**Comment by erevus-cn** [comment]
不大 只有有扫到结果才会存

**Comment by xiaoxiaoleo** [comment]
这样，，了解了，3q~
