### ISSUE TITLE
容器空间百分百导致rabbitmq无法启动

### ISSUE THREAD

**Issue by stayliv3** [erevus-cn/pocscan#14]
root@e2e4896826f7:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
none             19G   18G     0 100% /
tmpfs          1001M     0 1001M   0% /dev
shm              64M     0   64M   0% /dev/shm
tmpfs          1001M     0 1001M   0% /sys/fs/cgroup
none            233G  214G   20G  92% /www
/dev/sda1        19G   18G     0 100% /etc/hosts

mac ，是因为我本地剩余空间不到20G导致的么，还是bug。run起来之后exec进去df，就是100%，rabbitmq无法启动。

**Comment by erevus-cn** [comment]
应该是你电脑空间不足的，开发环境是rmbp,没有遇到你这种情况

**Comment by stayliv3** [comment]
能贴一下df -h 的结果么，我觉得used 18G不太可能啊。

**Comment by erevus-cn** [comment]
root@e777f55fbfbb:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
none             10G  653M  9.4G   7% /
tmpfs          1006M     0 1006M   0% /dev
shm              64M     0   64M   0% /dev/shm
/dev/vda1       7.8G  5.4G  2.0G  73% /www
/dev/vdb         10G  653M  9.4G   7% /etc/hosts
root@e777f55fbfbb:~#

**Comment by stayliv3** [comment]
thanks~

**Comment by stayliv3** [comment]
本地安装的方式可以添加到readme么，谢谢啦。

**Comment by erevus-cn** [comment]
看这里 https://github.com/erevus-cn/pocscan/issues/10 然后再把sqlmap的路径改一下就可以了

**Comment by stayliv3** [comment]
GOT~
