### ISSUE TITLE
一个错误提示

### ISSUE THREAD

**Issue by bingpo** [erevus-cn/pocscan#15]
全新的ubuntu环境
按照搭建的步骤出现错误提示
Internal Server Error

权限指定的目录为下载上面提供的下载连接解压后的文件夹
 这个是什么问题

**Comment by erevus-cn** [comment]
请提供你的运行命令和ls代码目录回显

**Comment by bingpo** [comment]
![Uploading 1.png…]()
![Uploading 2.png…]()
![Uploading 3-downloading.png…]()
![Uploading 4下载安装完毕.png…]()
![Uploading 5.png…]()
![Uploading 6.png…]()
![Uploading 7docker安装完毕.png…]()
![Uploading 8目录权限.png…]()
![Uploading 9映射端口.png…]()
![Uploading QQ截图20160428180318.png…]()
![Uploading 错误提示出现了.png…]()
![Uploading 最后.png…]()

**Comment by bingpo** [comment]
我还是弄个压缩包吧 把截图弄进去了 图片可能网络因素太慢了
上传不上去

**Comment by bingpo** [comment]
我还是弄个压缩包吧 把截图弄进去了 图片可能网络因素太慢了
上传不上去

**Comment by erevus-cn** [comment]
你的运行命令和ls代码目录回显很大吗？

**Comment by bingpo** [comment]
因为我都是每次运行一个命令之后就截图了 我把虚拟机的镜像恢复到最原始状态重新运行的

**Comment by bingpo** [comment]
evil@evil:~$ sudo chmod -R 0777 pocscan-master/
[sudo] evil 的密码： 
evil@evil:~$ sudo docker run -d -v pocscan-master:/www -p 8090:8000 -p 8088:8088 daocloud.io/aber/pocscan:latest
3e09a8551a3152632592ec4b0205b55a71d6f2961248dc47abda3ba9ed188461
evil@evil:~$ ls pocscan-master/
chtscan    pocscan      pocscanui  requirements.txt  web
manage.py  pocscan.crx  Readme.md  screenshots
evil@evil:~$ 

这个是最后一次运行的

**Comment by bingpo** [comment]
https://yunpan.cn/cPYeLuh7rFTM7 （提取码：ee88）  还是看图比较清晰 眼睛舒服 看看把 是哪里弄错了

**Comment by erevus-cn** [comment]
没有创建出数据库,家目录的下面给了文件夹权限，但是家目录的权限是没有的,你换个目录呗

**Comment by bingpo** [comment]
好的我再去试试 稍后给你回复  其实我第一次的时候 是直接切换到root用户执行的 当时是把目录放在了、usr/local目录下  出现的错误也是这个  我再试试把

**Comment by bingpo** [comment]
evil@evil:~$ sudo -i
root@evil:~# netstat -ap |grep 8090
tcp        0      0 localhost:34370         localhost:8090          ESTABLISHED 10410/firefox  
tcp6       0      0 [::]:8090               [::]:\*                  LISTEN      10545/docker-proxy
tcp6       0      0 localhost:8090          localhost:34370         ESTABLISHED 10545/docker-proxy
root@evil:~# exit
注销
evil@evil:~$ ls
examples.desktop  pocscan-master  公共的  模板  视频  图片  下载  音乐  桌面
evil@evil:~$ ls pocscan-master/
chtscan    pocscan      pocscanui  requirements.txt  web
manage.py  pocscan.crx  Readme.md  screenshots
evil@evil:~$

**Comment by bingpo** [comment]
sudo docker run -d -v pocscan-master:/www -p 8090:8000 -p 8088:8088 daocloud.io/aber/pocscan:latest
9fd934d10ad8da0a17065b8aee2d5e45d6479a4b63137936fc7caed9d102343d
