### ISSUE TITLE
不使用docker 各种报错。。扫描网站扫不出来。

### ISSUE THREAD

**Issue by imnewbe** [erevus-cn/pocscan#16]
用了插件也不会扫描。
查看任务状态查看不了，应是权限问题。
爬虫不会爬？
请指导。。你们这个插件怎么用。。

**Comment by imnewbe** [comment]
现在插件能用了。就是查看任务状态没法查看。不用docker可有办法解决？

**Comment by erevus-cn** [comment]
查看任务状态需要启动flower
python manage.py celery flower --broker=amqp://guest:guest@localhost:5672/

**Comment by imnewbe** [comment]
嗯阿，多谢！！！！
