### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by imnewbe** [erevus-cn/pocscan#17]

**Comment by imnewbe** [comment]
QAQxss扫描出来的结果怎么显示到网页？没太看懂sqlmap扫描的结果怎么返回到网页的。。所以不好改。return之后去哪里了。。。。Orz...

**Comment by erevus-cn** [comment]
XSS功能还没开发呢

**Comment by erevus-cn** [comment]
XSS功能还没开发呢

**Comment by imnewbe** [comment]
没有，我不是看见已经添加了个arachi.py了。所以我想自己把扫描结果return了
显示到页面不就行了？但是没看太懂。

**Comment by tlskbz** [comment]
那个文件算是彩蛋吧，至于显示结果，可以参考sqlc

**Comment by tlskbz** [comment]
@yckyos261 那个文件算是彩蛋吧，至于显示结果，可以参考sqlc

**Comment by imnewbe** [comment]
大哥，可以留个即时通讯方式吗。

**Comment by imnewbe** [comment]
@tlskbz
