### ISSUE TITLE
依然安装问题

### ISSUE THREAD

**Issue by bingpo** [erevus-cn/pocscan#18]
这次把所有执行命令与回显全部记录了下来

 第一步：sudo curl -sSL https://get.daocloud.io/docker | sh 
[sudo] evil 的密码： 
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
- sleep 20
  apparmor is enabled in the kernel and apparmor utils were already installed
- sudo -E sh -c apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  Executing: /tmp/tmp.6G2nPwLye3/gpg.1.sh --keyserver
  hkp://ha.pool.sks-keyservers.net:80
  --recv-keys
  58118E89F3A912897C070ADBF76221572C52609D
  gpg: 下载密钥‘2C52609D’，从 hkp 服务器 ha.pool.sks-keyservers.net
  gpg: 密钥 2C52609D：“Docker Release Tool (releasedocker) 
  第二布：evil@evil:~$ sudo systemctl start docker
  evil@evil:~$ 

第三步：
evil@evil:~$ sudo docker pull daocloud.io/aber/pocscan:latest
latest: Pulling from aber/pocscan
87192bdbe00f: Already exists 
28e09fddaacb: Already exists 
7e15ce58ccb2: Already exists 
a3ed95caeb02: Already exists 
0d81df0148f0: Already exists 
05d55b55325e: Already exists 
0047f80c8c96: Already exists 
45016dc7e432: Already exists 
de527e69a0ad: Already exists 
5f0b700d0b2a: Already exists 
14da188392b5: Already exists 
7ac0f3894e41: Already exists 
8ce127628480: Already exists 
91d710909cd4: Already exists 
64110291099f: Already exists 
5581a4d7d95e: Already exists 
035e085848f8: Already exists 
de94151bda73: Already exists 
56c967f48902: Already exists 
180cf3799a71: Already exists 
Digest: sha256:a85ca19ba62ca9b323ba483761d4dec678a553e6a08b4965ea21e62298b8b86a
Status: Image is up to date for daocloud.io/aber/pocscan:latest
evil@evil:~$ 

第四步：
evil@evil:~$ sudo chmod -R 0777 pocscan/
evil@evil:~$ 

第五步：
evil@evil:~$ git clone https://github.com/erevus-cn/pocscan.git
正克隆到 'pocscan'...
remote: Counting objects: 827, done.
remote: Total 827 (delta 0), reused 0 (delta 0), pack-reused 827
接收对象中: 100% (827/827), 2.61 MiB | 181.00 KiB/s, 完成.
处理 delta 中: 100% (300/300), 完成.
检查连接... 完成。

第六步：
evil@evil:~$ sudo docker run -d -v pocscan:/www -p 8090:8000 -p 8088:8088 daocloud.io/aber/pocscan:latest
62fea41456bfd47826fe8e4375e5661a10ba92135e841d4c462b85e3fff17f1e

运行ls
evil@evil:~$ ls pocscan/
chtscan    pocscan      pocscanui  requirements.txt  web
manage.py  pocscan.crx  Readme.md  screenshots
evil@evil:~$ 

最后打开127.0.0.1:8090 还是出现  Internal Server Error 这个提示  别的软件在当前目录下是可以正常运行的  作者说是数据库没有创建 可能是权限问题，实在是不清楚什么地方出问题了

**Comment by tlskbz** [comment]
@bingpo docker挂载目录的时候必须指定绝对路径

**Comment by bingpo** [comment]
解决了 正常进入界面 谢谢
