### ISSUE TITLE
django本机搭建不成功

### ISSUE THREAD

**Issue by cflq3** [erevus-cn/pocscan#27]
问个问题：
已更新至最新版，本机如下操作：
nohup rabbitmq-server  -detatched&
nohup python manage.py celery flower --broker=amqp://guest:guest@localhost:5672/ /&
python manage.py syncdb
nohup python manage.py runserver 0.0.0.0:8088&
可以正常登陆，扫描任务可以添加，但是没有进行扫描，没有扫描结果。。。

**Comment by erevus-cn** [comment]
扫描erevus.me

**Comment by cflq3** [comment]
扫描了后台可以看见地址，但是结果空白

**Comment by erevus-cn** [comment]
因为你起的端口不对 如果是不使用docker启动 端口需要使用8081，或者你可以去django的settings.py里面改端口
