### ISSUE TITLE
docker搭建报错，请教下是咋回事？

### ISSUE THREAD

**Issue by chencore** [erevus-cn/pocscan#30]
OperationalError at /login/
unable to open database file
Request Method: POST
Request URL:    http://192.168.2.114:8090/login/
Django Version: 1.8.3
Exception Type: OperationalError
Exception Value:  
unable to open database file
Exception Location: /usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py in get_new_connection, line 204
Python Executable:  /usr/local/bin/uwsgi
Python Version: 2.7.6
Python Path:  
['.',
 '',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']

**Comment by tlskbz** [comment]
@chencore 报错信息显示数据库文件存在问题，不知你启动镜像的时候 -v 参数是否指定的是绝对路径

**Comment by erevus-cn** [comment]
数据库没权限？或者找不到数据库

**Comment by chencore** [comment]
@tlskbz -v 指定的是绝对路径

**Comment by erevus-cn** [comment]
检查一下数据库权限是否是777

**Comment by chencore** [comment]
数据库文件在哪个目录下？我怎么没有找到数据库文件？
