### ISSUE TITLE
bugscan兼容性不好，跟没用一样。。

### ISSUE THREAD

**Issue by Jumbo-WJB** [erevus-cn/pocscan#31]
bugscan兼容性貌似还是不怎么好啊，我原封不动的bugscan插件是扫不出啥来的，跟没用一样。。但是我改写成pocsuite的，就是可以扫出来

**Comment by Jumbo-WJB** [comment]
我又试了几下，好多都不行。。。包括pocsuite。。。

**Comment by erevus-cn** [comment]
试试http://erevus.me
