### ISSUE TITLE
可否弄个纯环境下的安装说明

### ISSUE THREAD

**Issue by hackswM** [erevus-cn/pocscan#34]
docker对内核有要求 好多都弄不了 我本地下载安装ubutun都开动不了 daoclud下胶囊机成功过一次 然后就再也没成功过 全500 

可否弄个vps下纯环境安装的说明 ubuntu debian centos 都行

**Comment by tlskbz** [comment]
@hackswM 非docker环境安装可参考[add_bugscan分支](https://github.com/tlskbz/pocscan_dockerfile)
