### ISSUE TITLE
为什么在docker里会出现这样呢

### ISSUE THREAD

**Issue by yangxiaodi** [erevus-cn/pocscan#4]
环境是osx的，我安装的osx版本的，运行docker的vbox。
安装说明安装好了，能进login能改密码，但是在运行scan的时候，会报错
如图：
ValueError at /scan/
The view web.views.scan didn't return an HttpResponse object. It returned None instead.
Request Method: GET
Request URL:    http://192.168.99.100:8888/scan/
Django Version: 1.8.3
Exception Type: ValueError
Exception Value:  
The view web.views.scan didn't return an HttpResponse object. It returned None instead.
Exception Location: /usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in get_response, line 151
Python Executable:  /usr/local/bin/uwsgi
Python Version: 2.7.6
Python Path:  
['.',
 '',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/www']
Server time:    星期日, 20 三月 2016 22:38:38 +0800

图片不知道传上去了没(https://cbu01.alicdn.com/img/ibank/2016/593/308/2853803395_1759034333.jpg)

遇到这样的是docker环境z中没python吗？没接触过docker不懂

**Comment by erevus-cn** [comment]
端口换成8001试试 默认会开8001作为api的一个端口

**Comment by yangxiaodi** [comment]
我试了两种，将其中的一个端口改成8001
第一个无法访问
docker run -d -v /root/pocscan/:/www -p 8002:8001 daoclo
ud.io/aber/pocscan:1.1
第二个还是和原来那样报错。
docker run -d -v /root/pocscan/:/www -p 8001:8000 daoclo
ud.io/aber/pocscan:1.1
遇到这样的是docker环境z中没python吗？没接触过docker不懂

**Comment by erevus-cn** [comment]
Request Method: GET?  用get当然访问不了啦....这是个post接口
docker run -d -v /root/pocscan/:/www -p 8001:8000 daocloud.io/aber/pocscan:1.1 这种运行方法是对的 
你试试在管理界面添加扫描http://erevus.me测试一下是否能扫描
