### ISSUE TITLE
服务启动后发现没有监听8000端口，web后台找不到。。

### ISSUE THREAD

**Issue by tuhaolam** [erevus-cn/pocscan#50]
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:5555            0.0.0.0:*               LISTEN      13/python       
tcp        0      0 0.0.0.0:8088            0.0.0.0:*               LISTEN      12/python

**Comment by erevus-cn** [comment]
此项目已不维护，推荐这个项目https://github.com/jeffzh3ng/Fuxi-Scanner
