### ISSUE TITLE
用法说明不详细

### ISSUE THREAD

**Issue by ghost** [erevus-cn/pocscan#7]
原来是用butterfly实现交互功能的，之前的版本docker -ti一直失败很郁闷。另外，这个docker镜像docker restart永远挂掉啊。

**Comment by erevus-cn** [comment]
因为是docker启动只有一个superisor 所以不能用-ti形式启动，docker restart失败的问题我看看

**Comment by ghost** [comment]
数据存储是用了sqlite，以后才会用到mysql吗？commit了一个新镜像结果新镜像可以用docker restart了。

**Comment by tlskbz** [comment]
sqlite已经能满足当前需求，容器重启失败的问题和supervison有关

**Comment by ghost** [comment]
发现struts2拼写错误， web/templates/index.html里一句“如网站使用strus2,填入status2,扫描只会调用扫描struts2规则,不指定将使用所有扫描规则”三个struts2是不是不太对，另外，指的对应的扫描规则是否是通过文件名对应的？谢谢

**Comment by erevus-cn** [comment]
是和文件名对应的 类似sql语法  like '%word%'
